### ISSUE TITLE
Footer shows up two times

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/emp-tools#51] opened 2020-07-23 11:52 UTC
At the same time, improving the footer would be great.
![image](https://user-images.githubusercontent.com/12886084/88283474-b8ead500-cceb-11ea-9981-678f9f1df58b.png)

**Comment by nicholaspai** [comment] 2020-07-23 13:18
I am unable to reproduce this bug can you share more details?

**Comment by chrismaree** [comment] 2020-07-23 13:19
it only is present on `master`, not `develop`. If you go to http://tools.umaproject.org/ you'll see the issue there in production

**Comment by chrismaree** [comment] 2020-07-23 13:19
> I am unable to reproduce this bug can you share more details?

it only is present on `master`, not `develop`. If you go to http://tools.umaproject.org/ you'll see the issue there in production

**Comment by nicholaspai** [comment] 2020-07-23 13:57
> > I am unable to reproduce this bug can you share more details?
> 
> it only is present on `master`, not `develop`. If you go to http://tools.umaproject.org/ you'll see the issue there in production

Gotta be a merge conflict

**Comment by nicholaspai** [comment] 2020-07-24 03:52
Closed by #52

**Closed by nicholaspai** 2020-07-24 03:52 UTC
Labels: bug
